
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ template "lm-webhook.name" . }}-serving-cert
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
    - {{ .Values.service.name }}.{{ .Release.Namespace }}.svc
    - {{ .Values.service.name }}.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    name: {{ template "lm-webhook.name" . }}-selfsigned-issuer
  secretName: {{ template "lm-webhook.name" . }}-tls-cert
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ template "lm-webhook.name" . }}-selfsigned-issuer
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
