{{- if .Values.lmreloader }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "lm-webhook.name" . }}-lmreloader
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "lm-webhook.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "lm-webhook.chart" . }}
{{- if .Values.labels }}
{{ toYaml .Values.labels| indent 4 }}
{{- end }}

data:
{{- if .Values.lmreloader.config }}   
  lmreloaderconfig.yaml: |
{{ .Values.lmreloader.config | indent 4 }}
{{- end }}
{{- end }}