{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "lm-webhook.name" . }}
  namespace: {{ .Release.Namespace }}
{{- if .Values.labels}}
  labels:
    app.kubernetes.io/name: {{ include "lm-webhook.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "lm-webhook.chart" . }}
{{ toYaml .Values.labels | indent 4 }}
{{- end}}
{{- with .Values.serviceAccount.annotations }}
  annotations:
{{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}
