{{- if and .Values.mutatingWebhook.enabled .Values.mutatingWebhook.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ template "lm-k8s-webhook.name" . }}-serving-cert
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
    - {{ .Values.service.name }}.{{ .Release.Namespace }}.svc
    - {{ .Values.service.name }}.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    {{- if .Values.mutatingWebhook.certManager.issuerRef }}
    {{- toYaml .Values.mutatingWebhook.certManager.issuerRef | nindent 4 }}
    {{- else }}
    kind: Issuer
    name: {{ template "lm-k8s-webhook.name" . }}-selfsigned-issuer
    {{- end }}
  secretName: {{ template "lm-k8s-webhook.name" . }}-tls-cert

{{- if not .Values.mutatingWebhook.certManager.issuerRef }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ template "lm-k8s-webhook.name" . }}-selfsigned-issuer
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
{{- end }}
{{- end }}