apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "lm-k8s-webhook.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "lm-k8s-webhook.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "lm-k8s-webhook.chart" . }}
{{- if .Values.labels}}
{{ toYaml .Values.labels| indent 4 }}
{{- end }}

data:
  cluster_name: {{ required "A valid .Values.cluster_name entry is required!" .Values.cluster_name }}
{{- if .Values.lmK8sWebhook.config }}   
  lm-k8s-webhook-config.yaml: |
{{ .Values.lmK8sWebhook.config | indent 4 }}
{{- end }}